- alias: Tasmota State on HA Restart
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/backlog
      payload: 'power1 ;power2 ;power3 ;power4 ;power5; dimmer; state '
  id: d87abbaa17ac4d34ba4b588ae5301a26
- alias: Entryway Pico On
  trigger:
  - platform: event
    event_type: lutron_caseta_button_event
    event_data:
      device_id: 1dc460513b811e8f7f8480ff0b4d79ae
      button_type: 'on'
  action:
  - service: light.turn_on
    entity_id: light.entryway_light
  id: e4e902d9f5a541a483ae2700559f39b3
- alias: Entryway Pico Off
  trigger:
  - platform: event
    event_type: lutron_caseta_button_event
    event_data:
      device_id: 1dc460513b811e8f7f8480ff0b4d79ae
      button_type: 'off'
  action:
  - service: light.turn_off
    entity_id: light.entryway_light
  id: 752f303011334befa74d9a396195156b
- alias: Front Foyer Pico 2 On
  trigger:
  - platform: event
    event_type: lutron_caseta_button_event
    event_data:
      device_id: 77d0993bca99a69dd103fda070c3a8c6
      button_type: 'on'
  action:
  - service: light.turn_on
    entity_id: light.living_room_lamp
  id: afba786326554188b968db8633c298d6
- alias: Front Foyer Pico 2 Favorite
  trigger:
  - platform: event
    event_type: lutron_caseta_button_event
    event_data:
      device_id: 77d0993bca99a69dd103fda070c3a8c6
      button_type: stop
  action:
  - service: light.turn_on
    entity_id: light.living_room
  id: 40ba0dacde9941868852ae957af830f5
- alias: Front Foyer Pico 2 Off
  trigger:
  - platform: event
    event_type: lutron_caseta_button_event
    event_data:
      device_id: 77d0993bca99a69dd103fda070c3a8c6
      button_type: 'off'
  action:
  - service: light.turn_off
    entity_id:
    - light.living_room
    - light.living_room_lamp
  id: cbfa9d06009f4b289860e429a1408544
- alias: Master Bedroom Pico 1 Off
  trigger:
  - platform: event
    event type: lutron_caseta_button_event
    event_data:
      device_id: a4f5d906df74cdfb63a94edb9b809af8
      button_type: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.bedroom_2
  id: 65b7259f16d14f79b4c6044e8f7c1618
- id: '1587828654963'
  alias: Kodi
  description: Turn the lights off when Kodi plays
  trigger:
  - entity_id: media_player.kodi
    from: idle
    platform: state
    to: playing
  condition: []
  action:
  - data: {}
    entity_id: light.living_room_hue
    service: light.turn_off
- id: '1587830481783'
  alias: Netflix
  description: Dim the lights when netflix/hulu/amazon prime plays
  trigger:
  - entity_id: media_player.living_room_tv
    from: 'on'
    platform: state
    to: playing
  condition: []
  action:
  - data: {}
    entity_id: light.living_room_hue
    service: light.turn_off
- alias: Bathroom Lights Test
  trigger:
    platform: state
    entity_id: binary_sensor.aqara_motion_bathroom_occupancy
    to: 'on'
  condition:
    condition: time
    after: '7:00:00'
    before: '19:00:00'
  action:
    service: light.turn_on
    entity_id: light.bathroom_lights
  id: 121e4bac919f4aeaa5a8314b6b92b6ee
- alias: Bathroom Lights Test2
  trigger:
    platform: state
    entity_id: binary_sensor.aqara_motion_bathroom_occupancy
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    entity_id: light.bathroom_lights
  id: b3b37d5fdb034097ac5d852e4bc314a8
- alias: Samsung Low Battery
  trigger:
    platform: numeric_state
    entity_id: sensor.sm_g965u1_battery_level
    below: 21
  action:
    service: notify.pusbullet
    data_template:
      title: Charge Battery
      message: Charge phone because battery is {{ states('sensor.sm_g965u1_battery_level')
        }} percent
  id: c140605d1df94ec1bdba080f8d300c31
- alias: Samsung Hi Battery
  trigger:
    platform: numeric_state
    entity_id: sensor.sm_g965u1_battery_level
    above: 79
  action:
    service: notify.pusbullet
    data_template:
      title: Stop Charging Battery
      message: Stop charging phone because battery is {{ states('sensor.sm_g965u1_battery_level')
        }} percent
  id: c874a4dd6226414f819904e2ac88b61d
- alias: Enable Zigbee joining
  trigger:
    platform: state
    entity_id: input_boolean.zigbee_permit_join
    to: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'true'
  - service: timer.start
    data:
      entity_id: timer.zigbee_permit_join
  id: bd1e4918d3564fc9afa952c5d1a22e1e
- alias: Disable Zigbee joining
  trigger:
  - entity_id: input_boolean.zigbee_permit_join
    platform: state
    to: 'off'
  action:
  - data:
      payload: 'false'
      topic: zigbee2mqtt/bridge/config/permit_join
    service: mqtt.publish
  - data:
      entity_id: timer.zigbee_permit_join
    service: timer.cancel
  id: ea2b1971d5fd41e9aa280168cc1e6ee2
- alias: Disable Zigbee joining by timer
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee_permit_join
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'false'
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.zigbee_permit_join
  id: 1948dd2eb3c54ce5a659e1b5e2548e2d
- alias: Kitchen Lights On
  trigger:
    platform: state
    entity_id: binary_sensor.aqara_kitchen_occupancy
    to: 'on'
  condition:
    condition: time
    after: '7:00:00'
    before: '19:00:00'
  action:
    service: light.turn_on
    entity_id: light.kitchen_main_lights
  id: 584be41f93094febb42a04203ec1eacf
- alias: Kitchen Lights Off
  trigger:
    platform: state
    entity_id: binary_sensor.aqara_kitchen_occupancy
    to: 'off'
    for:
      minutes: 1
  action:
    service: light.turn_off
    entity_id: light.kitchen_main_lights
  id: 6a50000792cb4c6b92ac2c4cf8b003be
- alias: Turn off light via actionable notificaiton
  trigger:
    platform: event
    event_type: alexa_actionable_notification
    event_data:
      event_id: actionable_notification_door_left_open
      event_response_type: ResponseYes
  action:
  - service: light.turn_off
    entity_id: light.master_bedroom_ceiling_fan_light
  id: 6eea476eeb49438084c03b6e072ae054
- id: '1596583311386'
  alias: Action Test 2
  description: ''
  trigger:
  - event_data:
      event_id: actionable_notification_door_left_open
      event_response: ResponseYes
    event_type: alexa_actionable_notifcation
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: light.master_bedroom_ceiling_fan_light
    service: light.turn_off
  mode: single
- alias: Nursery Low Temperature
  id: 4df6ec1850624467b23d601a5c548ff6
  triggers:
    - trigger: numeric_state
      entity_id: sensor.nursery_temperature
      below: 67
  actions:
    - action: notify.pushbullet
      data:
        title: Too Cold
        message: "The Temperature in the Nursery is {{ states('sensor.nursery_temperature') }} Degrees"

- alias: Nursery Hi Temperature
  id: 110151f29f2f4a049cd4a0c92c42d70f
  triggers:
    - trigger: numeric_state
      entity_id: sensor.nursery_temperature
      above: 73
  actions:
    - action: notify.pushbullet
      data:
        title: Too Hot
        message: "The Temperature in the Nursery is {{ states('sensor.nursery_temperature') }} Degrees"
# - alias: Nursery Space Heater On
#   id: 7b9d5c8427454cc98ea3a8e567c291f6
#   triggers:
#     - trigger: numeric_state
#       entity_id: sensor.nursery_temperature
#       below: 68
#   actions:
#     - action: switch.turn_on
#       target:
#         entity_id: switch.living_room_1

# - alias: Nursery Space Heater Off
#   id: c37e2f5031ca4537a62679216733f27c
#   triggers:
#     - trigger: numeric_state
#       entity_id: sensor.nursery_temperature
#       above: 70
#   actions:
#     - action: switch.turn_off
#       target:
#         entity_id: switch.living_room_1
- alias: Lights Off When We Leave
  trigger:
    platform: state
    entity_id: group.family
    to: not_home
  action:
  - service: light.turn_off
    entity_id:
    - light.bathroom_lights
    - light.dining_room_lights
    - light.master_bedroom_ceiling_fan_light
    - light.nursery_sconces
    - light.entryway_light
    - light.0x0017880108197b79_light
  - service: switch.turn_off
    entity_id:
    - switch.living_room_3
    - switch.bedroom_2
    - switch.bedroom_1
  id: 4e160fc575e44f6c97e227dd3e7b4a2c
- alias: Lights on When We Come Back
  trigger:
    platform: state
    entity_id: group.family
    to: home
  action:
  - service: light.turn_on
    entity_id:
    - light.bathroom_lights
    - light.dining_room_lights
    - light.master_bedroom_ceiling_fan_light
    - light.nursery_sconces
    - light.entryway_light
    - light.0x0017880108197b79_light
  - service: switch.turn_on
    entity_id:
    - switch.living_room_3
    - switch.bedroom_2
    - switch.bedroom_1
  id: 07d080f92875429e9f8bc1110c11b2fe
- alias: Boolean Test 3
  trigger:
    platform: state
    entity_id: binary_sensor.mailbox_contact
    to: 'on'
  action:
    service: input_boolean.toggle
    entity_id: input_boolean.motion_detected
  id: e22d6278271047e5afe1a1f628f47890
- alias: Reset Sensor At Midnight
  trigger:
  - platform: time
    at: 00:00:00
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.motion_detected
  id: f1538a2367274210a5ce29015ad28eea
- alias: Dishwasher State - Start
  trigger:
    platform: numeric_state
    entity_id: sensor.dishwasher_watts
    above: 5
    for:
      seconds: 4
  condition:
    condition: template
    value_template: '{{ states.sensor.dishwasher_state.state != ''Washing'' }}'
  action:
  - service: mqtt.publish
    data:
      topic: hass/state/Dishwasher
      payload: Washing
      retain: 'true'
  id: 3b1da440d6af41e58eaae4c3a24a1d74
- alias: Dishwasher State - Idle
  trigger:
    platform: numeric_state
    entity_id: sensor.dishwasher_watts
    below: 5
    for:
      minutes: 5
  action:
  - service: mqtt.publish
    data:
      topic: hass/state/Dishwasher
      payload: Idle
      retain: 'true'
  id: a6230cc1111a498ab3656ca4dedc76c9
- alias: Washer State - Start
  trigger:
    platform: numeric_state
    entity_id: sensor.washer_watts
    above: 5
    for:
      seconds: 4
  condition:
    condition: template
    value_template: '{{ states.sensor.washer_state.state != ''Washing'' }}'
  action:
  - service: mqtt.publish
    data:
      topic: hass/state/washer
      payload: Washing
      retain: 'true'
  id: c011de34442241f39454995237ec3c19
- alias: Washer State - Idle
  trigger:
    platform: numeric_state
    entity_id: sensor.washer_watts
    below: 5
    for:
      minutes: 5
  action:
  - service: mqtt.publish
    data:
      topic: hass/state/washer
      payload: Idle
      retain: 'true'
  id: 04b060g79675429e9f8bj1110t11f2sg
- alias: Washer Finished
  trigger:
    platform: state
    entity_id: sensor.washer_state
    from: Washing
    to: Idle
  condition:
  - condition: state
    entity_id: input_boolean.washer_clean
    state: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.washer_clean
  - service: input_boolean.turn_on
    entity_id: input_boolean.laundry_ready_to_move
  - service: notify.alexa_media_everywhere
    data:
      message: The clothes are ready to be moved to the dryer
      data:
        type: announce
        method: tts
  id: 62fd808d8971417eaa6a3be0373facfc
- id: '1673063887141'
  alias: New Automation
  description: ''
  trigger:
  - platform: webhook
    webhook_id: hello-world
  condition: []
  action:
  - type: turn_off
    device_id: 457db81b2802b8ba73202cc757e48f29
    entity_id: light.living_room_lamp
    domain: light
  mode: single
- id: '1673064927013'
  alias: New Automation2
  description: ''
  trigger:
  - platform: webhook
    webhook_id: hello-worlds
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.living_room_lamp
  mode: single
- id: '1673066807843'
  alias: Washer_Idling
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.washer_state
    from: Washing
    to: Idle
  - platform: state
    entity_id:
    - sensor.washer_state
    from: Outoforder
    to: Idle
  condition: []
  action:
  - service: rest_command.fast_api_idling
    data: {}
  mode: single
- id: '1674700249990'
  alias: Washer_Washing
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.washer_state
    from: Idle
    to: Washing
  - platform: state
    entity_id:
    - sensor.washer_state
    from: Outoforder
    to: Washing
  condition: []
  action:
  - service: rest_command.fast_api_washing
    data: {}
  mode: single
- id: '1682813764527'
  alias: Apt. Door
  description: ''
  trigger:
  - platform: tag
    tag_id: d3ec35c6-cbaf-4665-afd0-36693cf173e7
  condition: []
  action:
  - service: lock.unlock
    data: {}
    target:
      entity_id: lock.august_smart_lock_pro_3rd_gen
  mode: single
- id: '1685565438276'
  alias: Tag Door_Lock is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: c04731ec-de95-4ed7-ae70-bd732d25cd09
  condition: []
  action:
  - service: lock.lock
    data: {}
    target:
      entity_id: lock.august_smart_lock_pro_3rd_gen
  mode: single
- id: '1705718027844'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.washer_state
    from: Idle
    to: Outoforder
  - platform: state
    entity_id:
    - sensor.washer_state
    from: Washing
    to: Outoforder
  condition: []
  action:
  - service: rest_command.fast_api_ooo
    data: {}
  mode: single
- id: '1728849436336'
  alias: Master Bedroom Pico Off
  description: ''
  trigger:
  - platform: device
    device_id: a4f5d906df74cdfb63a94edb9b809af8
    domain: lutron_caseta
    type: press
    subtype: 'off'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.bedroom_2
    data: {}
  mode: single
- id: '1728849494678'
  alias: Master Bedroom Pico On
  description: ''
  trigger:
  - platform: device
    device_id: a4f5d906df74cdfb63a94edb9b809af8
    domain: lutron_caseta
    type: press
    subtype: 'on'
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id:
      - switch.bedroom_2
    data: {}
  mode: single
- id: '1728850885465'
  alias: Master Bedroom Pico 2 On
  description: ''
  trigger:
  - platform: device
    device_id: f77a405ed1412cbd42cc5b4062388b7d
    domain: lutron_caseta
    type: press
    subtype: 'on'
  condition: []
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.bedroom_1
  mode: single
- id: '1728851104319'
  alias: Master Bedroom Pico 2 Off
  description: ''
  trigger:
  - platform: device
    device_id: f77a405ed1412cbd42cc5b4062388b7d
    domain: lutron_caseta
    type: press
    subtype: 'off'
  condition: []
  action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.bedroom_1
  mode: single
